# Task 3: Employee Data Cleaning

## 1. Project Overview

This project focuses on cleaning a messy employee dataset using Python, pandas, and NumPy.

## 2. Objective

To identify data quality issues, handle missing values, remove duplicate records, standardize inconsistent values, investigate outliers, correct data types, and prepare an analysis-ready dataset.

## 3. Tools and Technologies

- Python
- pandas
- NumPy
- Jupyter Notebook

## 4. Data Cleaning Workflow

1. Load the raw dataset.
2. Generate an initial data quality report.
3. Handle missing values.
4. Remove duplicate records.
5. Standardize inconsistent values.
6. Detect and investigate outliers.
7. Correct data types.
8. Compare data quality before and after cleaning.
9. Save the cleaned dataset as a CSV file.

# Import Libraries

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

##  Load the Dataset

In this step, the raw employee dataset is loaded into a pandas DataFrame. The original dataset is preserved so that all cleaning operations can be documented and verified.

In [4]:
PROJECT_DIR = Path("..")

file_path = (
    PROJECT_DIR
    / "data"
    / "raw"
    / "messy_employee_data.csv"
)

df = pd.read_csv(r"C:\Users\bhumi\Downloads\OASIS Internshp Projects\Messy_Employee_dataset.csv")

print("Dataset loaded successfully!")
print("Rows and columns:", df.shape)

df.head()

Dataset loaded successfully!
Rows and columns: (1020, 12)

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [7]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Department_Region',
       'Status', 'Join_Date', 'Salary', 'Email', 'Phone', 'Performance_Score',
       'Remote_Work'],
      dtype='object')

In [8]:
df.tail()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
1015,EMP2015,David,Miller,30.0,HR-California,Active,8/19/2023,NaN,david.miller@example.com,-3546212759,Good,True
1016,EMP2016,David,Johnson,30.0,Cloud Tech-Texas,Inactive,11/7/2021,100215.06,david.johnson@example.com,-2508261122,Good,True
1017,EMP2017,Charlie,Williams,40.0,Finance-New York,Active,10/4/2023,114587.11,charlie.williams@example.com,-1261632487,Average,False
1018,EMP2018,Alice,Garcia,30.0,HR-Florida,Inactive,12/16/2024,71318.79,alice.garcia@example.com,-8995729892,Good,True
1019,EMP2019,Heidi,Jones,30.0,DevOps-Illinois,Pending,2/22/2021,77764.24,heidi.jones@example.com,-7629745492,Average,False

In [9]:
df.dtypes

Employee_ID           object
First_Name            object
Last_Name             object
Age                  float64
Department_Region     object
Status                object
Join_Date             object
Salary               float64
Email                 object
Phone                  int64
Performance_Score     object
Remote_Work             bool
dtype: object

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

## Initial Data Quality Assessment

This step evaluates the raw dataset by examining its dimensions, missing values, duplicate records, data types, and numerical distributions.

The results will serve as the baseline for measuring the effectiveness of the cleaning process.

In [ ]:
# Missing values per column

In [11]:
df.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

In [14]:
# Missing-value percentage

(df.isnull().mean() * 100).round(2)

Employee_ID           0.00
First_Name            0.00
Last_Name             0.00
Age                  20.69
Department_Region     0.00
Status                0.00
Join_Date             0.00
Salary                2.35
Email                 0.00
Phone                 0.00
Performance_Score     0.00
Remote_Work           0.00
dtype: float64

In [15]:
# Duplicate rows

df.duplicated().sum()

0

In [16]:
# Data types and non-null counts

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

In [17]:
# Numeric value summary

df.describe()

              Age         Salary         Phone
count  809.000000     996.000000  1.020000e+03
mean    32.484549   85155.056396 -4.942253e+09
std      5.656860   19873.727918  2.817326e+09
min     25.000000   50047.320000 -9.994973e+09
25%     25.000000   68392.487500 -7.341992e+09
50%     30.000000   85547.870000 -4.943997e+09
75%     40.000000  100974.027500 -2.520391e+09
max     40.000000  119971.650000 -3.896086e+06

In [18]:
# Summary of all columns

df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Employee_ID,1020,1020,EMP1000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
First_Name,1020,8,Frank,142,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Last_Name,1020,8,Brown,148,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,809.0,NaN,NaN,NaN,32.484549,5.65686,25.0,25.0,30.0,40.0,40.0
Department_Region,1020,36,HR-Florida,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Status,1020,3,Pending,356,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Join_Date,1020,760,6/10/2024,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Salary,996.0,NaN,NaN,NaN,85155.056396,19873.727918,50047.32,68392.4875,85547.87,100974.0275,119971.65
Email,1020,64,grace.brown@example.com,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Phone,1020.0,NaN,NaN,NaN,-4942252959.221569,2817326049.742001,-9994973202.0,-7341991816.5,-4943996508.5,-2520390678.75,-3896086.0
Performance_Score,1020,4,Good,270,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Remote_Work,1020,2,True,513,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Preserve the original data and record baseline metrics

df_raw = df.copy()
df_clean = df.copy()

before_metrics = {
    "Rows": len(df_clean),
    "Columns": len(df_clean.columns),
    "Missing Values": int(df_clean.isnull().sum().sum()),
    "Duplicate Rows": int(df_clean.duplicated().sum())
}

pd.Series(before_metrics, name="Before Cleaning")

Rows              1020
Columns             12
Missing Values     235
Duplicate Rows       0
Name: Before Cleaning, dtype: int64

# Handle missing values

In [20]:
df_clean.isnull().sum()

Employee_ID            0
First_Name             0
Last_Name              0
Age                  211
Department_Region      0
Status                 0
Join_Date              0
Salary                24
Email                  0
Phone                  0
Performance_Score      0
Remote_Work            0
dtype: int64

##  Missing Data Handling

The missing-value treatment is selected separately for each column based on its meaning and data distribution.

- Median imputation may be used for suitable numeric columns because it is less sensitive to extreme values than the mean.
- Mode imputation may be used for categorical columns when the most frequent category is a reasonable replacement.
- Employee identifiers will not be imputed using statistical averages.
- Rows will be removed only when justified by the data quality requirements.

All decisions will be documented after inspecting the actual missing-value patterns.

In [21]:
df_clean.select_dtypes(include="number").columns

Index(['Age', 'Salary', 'Phone'], dtype='object')

In [22]:
df_clean.select_dtypes(include="object", exclude=None).columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Department_Region', 'Status',
       'Join_Date', 'Email', 'Performance_Score'],
      dtype='object')

# Unique values in categorical columns

In [24]:
df["Department_Region"].value_counts()

HR-Florida               41
DevOps-California        35
Sales-Nevada             35
Admin-Nevada             34
Admin-California         34
DevOps-Florida           34
Sales-Florida            33
DevOps-Illinois          33
HR-New York              33
Finance-Illinois         33
DevOps-New York          33
Finance-California       32
Sales-California         31
Sales-Illinois           30
Cloud Tech-Texas         29
Admin-Illinois           29
Finance-Nevada           29
Cloud Tech-California    29
Finance-Texas            29
Cloud Tech-Florida       28
DevOps-Texas             27
DevOps-Nevada            27
HR-California            26
Sales-New York           26
Admin-Florida            25
HR-Nevada                24
HR-Illinois              24
Cloud Tech-New York      24
Finance-Florida          24
HR-Texas                 23
Finance-New York         23
Sales-Texas              23
Admin-New York           22
Admin-Texas              22
Cloud Tech-Nevada        20
Cloud Tech-Illinois      16
Name: Department_Region, dtype: int64

In [25]:
df["Status"].value_counts()

Pending     356
Active      352
Inactive    312
Name: Status, dtype: int64

# Check phone values

In [26]:
df["Phone"].describe()

count    1.020000e+03
mean    -4.942253e+09
std      2.817326e+09
min     -9.994973e+09
25%     -7.341992e+09
50%     -4.943997e+09
75%     -2.520391e+09
max     -3.896086e+06
Name: Phone, dtype: float64

In [27]:
(df["Phone"] < 0).sum()

1020

# Keep original data safe

In [28]:
df_raw = df.copy()

df_clean = df.copy()

df_clean.shape

(1020, 12)

# Handle missing values

# Age column

In [29]:
df_clean["Age"].isnull().sum()

211

In [30]:
age_median = df_clean["Age"].median()

age_median

30.0

In [31]:
df_clean["Age"] = df_clean["Age"].fillna(age_median)

df_clean["Age"].isnull().sum()

0

# Salary column

In [33]:
salary_median = df_clean["Salary"].median()

salary_median

85547.87

In [34]:
df_clean["Salary"] = df_clean["Salary"].fillna(salary_median)

df_clean["Salary"].isnull().sum()

0

In [ ]:
# Missing Age and Salary values were imputed using their respective medians. Median imputation retains the employee records while reducing sensitivity to extreme numerical values.

# Remove duplicate rows

In [35]:
duplicate_count = df_clean.duplicated().sum()

duplicate_count

0

In [36]:
df_clean = df_clean.drop_duplicates()

df_clean.duplicated().sum()

0

In [37]:
df_clean["Employee_ID"].duplicated().sum()

0

In [ ]:
# Exact duplicate rows were checked and removed if present. Employee IDs were also checked for duplicate identifiers.

# Standardize text columns

In [38]:
text_columns = [
    "Employee_ID",
    "First_Name",
    "Last_Name",
    "Department_Region",
    "Status",
    "Email",
    "Performance_Score"
]

for column in text_columns:
    df_clean[column] = df_clean[column].astype("string").str.strip()

In [39]:
df_clean[[
    "Employee_ID",
    "First_Name",
    "Last_Name",
    "Department_Region",
    "Status",
    "Email",
    "Performance_Score"
]].head()

,Employee_ID,First_Name,Last_Name,Department_Region,Status,Email,Performance_Score
0,EMP1000,Bob,Davis,DevOps-California,Active,bob.davis@example.com,Average
1,EMP1001,Bob,Brown,Finance-Texas,Active,bob.brown@example.com,Excellent
2,EMP1002,Alice,Jones,Admin-Nevada,Pending,alice.jones@example.com,Good
3,EMP1003,Eva,Davis,Admin-Nevada,Inactive,eva.davis@example.com,Good
4,EMP1004,Frank,Williams,Cloud Tech-Florida,Active,frank.williams@example.com,Poor

In [40]:
df_clean["Status"].value_counts()

Pending     356
Active      352
Inactive    312
Name: Status, dtype: Int64

In [41]:
df_clean["Performance_Score"].value_counts()

Good         270
Average      267
Excellent    267
Poor         216
Name: Performance_Score, dtype: Int64

# Correct data types

In [ ]:
# 1  Employee ID as string

In [42]:
df_clean["Employee_ID"] = df_clean["Employee_ID"].astype("string")

In [ ]:
# 2  Join date as datetime

In [43]:
df_clean["Join_Date"] = pd.to_datetime(
    df_clean["Join_Date"],
    errors="coerce"
)

In [44]:
df_clean["Join_Date"].isnull().sum()

0

# Salary and Age as numeric

In [45]:
df_clean["Age"] = pd.to_numeric(
    df_clean["Age"],
    errors="coerce"
)

df_clean["Salary"] = pd.to_numeric(
    df_clean["Salary"],
    errors="coerce"
)

In [46]:
df_clean["Phone"] = df_clean["Phone"].astype("string")

invalid_phone = (
    df_clean["Phone"].str.fullmatch(r"\+?\d{10,15}", na=False) == False
)

invalid_phone.sum()

1020

In [47]:
df_clean.loc[invalid_phone, "Phone"] = pd.NA

In [48]:
df_clean["Phone"].head()

0    <NA>
1    <NA>
2    <NA>
3    <NA>
4    <NA>
Name: Phone, dtype: string

In [49]:
df_clean["Phone"].isnull().sum()

1020

In [72]:
df_raw["Phone"].head(10)

0   -1651623197
1   -1898471390
2   -5596363211
3   -3476490784
4   -1586734256
5   -5409003485
6   -4518376063
7   -4134327559
8   -4177656123
9   -8156985699
Name: Phone, dtype: int64

In [73]:
(df_raw["Phone"] < 0).sum()

1020

In [74]:
df_raw["Phone"].describe()

count    1.020000e+03
mean    -4.942253e+09
std      2.817326e+09
min     -9.994973e+09
25%     -7.341992e+09
50%     -4.943997e+09
75%     -2.520391e+09
max     -3.896086e+06
Name: Phone, dtype: float64

In [75]:
df_clean["Phone"] = df_raw["Phone"].astype("string")

In [76]:
(df_raw["Phone"] < 0).sum()

1020

In [77]:
df_clean["Phone"] = df_raw["Phone"].astype("string")

In [78]:
phone_quality_report = pd.DataFrame({
    "Metric": [
        "Total phone records",
        "Negative phone values",
        "Missing phone values"
    ],
    "Count": [
        len(df_clean),
        (pd.to_numeric(df_clean["Phone"], errors="coerce") < 0).sum(),
        df_clean["Phone"].isna().sum()
    ]
})

phone_quality_report

                  Metric  Count
0    Total phone records   1020
1  Negative phone values   1020
2   Missing phone values      0

In [82]:
df_clean["Phone"].dtype

string[python]

In [93]:
df_clean["Phone"] = df_clean["Phone"].astype("string").str.replace("-", "", regex=False)

In [90]:
df_clean["Phone"].head(10)

0    1651623197
1    1898471390
2    5596363211
3    3476490784
4    1586734256
5    5409003485
6    4518376063
7    4134327559
8    4177656123
9    8156985699
Name: Phone, dtype: string

In [91]:
df_clean["Phone"].str.len().value_counts(dropna=False)

10      928
9        78
8        12
7         2
<NA>      0
Name: Phone, dtype: Int64

In [94]:
valid_phone = df_clean["Phone"].str.fullmatch(
    r"[6-9]\d{9}", na=False
)

print("Valid phone numbers:", valid_phone.sum())
print("Invalid phone numbers:", (~valid_phone).sum())

Valid phone numbers: 391
Invalid phone numbers: 629

In [97]:
print("Invalid phone formats:",
      (~df_clean["Phone"].str.fullmatch(r"[6-9]\d{9}", na=False)).sum())

print("Missing phone values:",
      df_clean["Phone"].isna().sum())

Invalid phone formats: 629
Missing phone values: 629

In [98]:
print("Total records:", len(df_clean))
print("Valid phone numbers:", df_clean["Phone"].notna().sum())
print("Missing phone numbers:", df_clean["Phone"].isna().sum())

Total records: 1020
Valid phone numbers: 391
Missing phone numbers: 629

In [92]:
df_clean["Phone"].str.contains("-", na=False).sum()

0

In [89]:
df_clean["Phone"].isna().sum()

0

In [105]:
# Count empty phone numbers
print("Missing phone numbers:", df_clean["Phone"].isna().sum())

# Count empty strings
print("Empty phone numbers:", (df_clean["Phone"].astype(str).str.strip() == "").sum())

Missing phone numbers: 629
Empty phone numbers: 0

In [106]:
print("Original missing phone numbers:", df_raw["Phone"].isna().sum())
print("Cleaned missing phone numbers:", df_clean["Phone"].isna().sum())

Original missing phone numbers: 0
Cleaned missing phone numbers: 629

In [107]:
# Restore Phone column from original dataset
df_clean["Phone"] = df_raw["Phone"].copy()

# Remove negative sign and decimal .0 if present
df_clean["Phone"] = (
    df_clean["Phone"]
    .astype(str)
    .str.replace(r"\.0$", "", regex=True)
    .str.replace(r"^-", "", regex=True)
)

# Check missing values
print("Missing phone numbers:", df_clean["Phone"].isna().sum())
print("Empty phone numbers:", (df_clean["Phone"].str.strip() == "").sum())

# Save cleaned CSV again
df_clean.to_csv(
    r"C:\Users\bhumi\Downloads\OASIS Internshp Projects\cleaned_employee_data.csv",
    index=False
)

print("✅ Cleaned CSV saved successfully!")

Missing phone numbers: 0
Empty phone numbers: 0
✅ Cleaned CSV saved successfully!

# Detect outliers using IQR

The IQR method was used to identify potential outliers in Age and Salary. Outliers were retained unless further investigation showed that the values were invalid. This avoids removing legitimate employee records without evidence.

In [50]:
numeric_columns = ["Age", "Salary"]

outlier_results = []

for column in numeric_columns:
    Q1 = df_clean[column].quantile(0.25)
    Q3 = df_clean[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df_clean[
        (df_clean[column] < lower_limit) |
        (df_clean[column] > upper_limit)
    ]

    outlier_results.append({
        "Column": column,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outlier Count": len(outliers)
    })

outlier_report = pd.DataFrame(outlier_results)

outlier_report

   Column  Lower Limit  Upper Limit  Outlier Count
0     Age      22.5000      42.5000              0
1  Salary   21469.0875  147714.8075              0

# Check invalid ranges

In [51]:
df_clean[
    (df_clean["Age"] < 18) |
    (df_clean["Age"] > 100)
]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

In [52]:
df_clean[df_clean["Salary"] < 0]

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Department_Region, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work]
Index: []

# Before-and-after report

In [53]:
before_metrics = {
    "Rows": len(df_raw),
    "Columns": len(df_raw.columns),
    "Missing Values": int(df_raw.isnull().sum().sum()),
    "Duplicate Rows": int(df_raw.duplicated().sum())
}

after_metrics = {
    "Rows": len(df_clean),
    "Columns": len(df_clean.columns),
    "Missing Values": int(df_clean.isnull().sum().sum()),
    "Duplicate Rows": int(df_clean.duplicated().sum())
}

comparison = pd.DataFrame({
    "Before Cleaning": before_metrics,
    "After Cleaning": after_metrics
})

comparison

                Before Cleaning  After Cleaning
Rows                       1020            1020
Columns                      12              12
Missing Values              235            1020
Duplicate Rows                0               0

# Missing values by column after cleaning

In [54]:
df_clean.isnull().sum()

Employee_ID             0
First_Name              0
Last_Name               0
Age                     0
Department_Region       0
Status                  0
Join_Date               0
Salary                  0
Email                   0
Phone                1020
Performance_Score       0
Remote_Work             0
dtype: int64

# Final data types

In [55]:
df_clean.dtypes

Employee_ID                  string
First_Name                   string
Last_Name                    string
Age                         float64
Department_Region            string
Status                       string
Join_Date            datetime64[ns]
Salary                      float64
Email                        string
Phone                        string
Performance_Score            string
Remote_Work                    bool
dtype: object

# Final row and column count

In [56]:
df_clean.shape

(1020, 12)

# Final duplicate check

In [57]:
df_clean.duplicated().sum()

0

# Save the cleaned CSV

In [102]:
df_clean.to_csv(
    r"C:\Users\bhumi\Downloads\OASIS Internshp Projects\cleaned_employee_data.csv",
    index=False
)

In [103]:
df_clean.to_csv(
    r"C:\Users\bhumi\Downloads\OASIS Internshp Projects\cleaned_employee_data.csv",
    index=False
)

print("✅ Cleaned CSV file saved successfully!")

✅ Cleaned CSV file saved successfully!

In [104]:
import os

print(os.path.exists(
    r"C:\Users\bhumi\Downloads\OASIS Internshp Projects\cleaned_employee_data.csv"
))

True